### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-libertadpozos#1]
Buen trabajo @libertadpozos 

Algunas pistas para acabarlo:

- [x] Mueve el título de la página (Mi lista de Pokemons) fuera del componente List.
- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Elimina el código comentado
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click al componente Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato a Pokemon por props
5. Pintar la tarjeta con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by libertadpozos** [comment]
Hey @nasivuela!
Hope you are doing fine. I think I have finished the exercise, can you check it, please?. Meanwhile, I will continue to improve it in another branch :)

**Comment by nasivuela** [comment]
Está genial ;)

![](https://media.giphy.com/media/k2Da0Uzaxo9xe/giphy.gif)
